//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToyShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        public int MaDonHang { get; set; }
        public string MaNguoiDung { get; set; }
        public decimal TongTien { get; set; }
        public string GhiChu { get; set; }
        public string SoDienThoai { get; set; }
        public string DiaChi { get; set; }
        public string PhuongThucThanhToan { get; set; }
        public System.DateTime NgayThanhToan { get; set; }
        public string TinhTrang { get; set; }
        public Nullable<System.DateTime> NgayGiaoHang { get; set; }
    }
}
