//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToyShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public string MaSanPham { get; set; }
        public string MaHangSanXuat { get; set; }
        public string MaLoaiSanPham { get; set; }
        public string TenSanPham { get; set; }
        public string Hinh { get; set; }
        public decimal Gia { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> LuotXem { get; set; }
        public int TinhTrang { get; set; }
    
        public virtual HangSanXuat HangSanXuat { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
    }
}
